name: "FibBot"
description: "A GitHub Action to calculate Fibonacci numbers from PR content."
author: "Vitalis"
inputs:
  pr_number:
    description: "The number of the pull request."
    required: false
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)."
    required: false
    default: "true"
  max_threshold:
    description: "Maximum threshold for Fibonacci calculation."
    required: false
    default: "100"
  github_token:
    description: "GitHub token to interact with GitHub API."
    required: true
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}
  env:
    PR_NUMBER: ${{ inputs.pr_number }}
    GITHUB_TOKEN: ${{ inputs.github_token }}